[package]
name = "zobrist"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
chess = { workspace = true }
indicatif = { workspace = true , features = ["rayon"] }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
csv = { workspace = true }
clap = { workspace = true, features = ["derive"] }

[[bin]]
name = "zobrist"
path = "src/main.rs"
test = false
