[workspace]
members = ["crates/*"]
default-members = ["crates/engine-cli"]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Paul Tsouchlos <developer.paul.123@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/ptsouchlos/byte-knight"

[workspace.dependencies]
# Workspace member crates
chess = { path = "crates/chess"}
engine = {path = "crates/engine"}
byte-knight = { path = "crates/engine-cli"}
generate-magics = { path = "crates/generate-magics" }
hce-tuner = { path = "crates/hce-tuner" }
perft-bench = { path = "crates/perft-bench" }
zobrist = { path = "crates/zobrist" }

# external dependencies
anyhow = "1.0.102"
arrayvec = "0.7.6"
clap = "4.6.1"
colored = "3.1.1"
console = "0.16.3"
criterion = "0.8"
csv = "1.4.0"
indicatif = "0.18.4"
itertools = "0.15.0"
rand = "0.10.1"
rayon = "1.12.0"
serde = "1.0.228"
textplots = "0.8.7"
toml = "1.1"
thiserror = "2.0.20"
uci-parser = "1.1.0"
ctrlc = "3.5.2"
rapidhash = "4.4.1"

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
debug-assertions = false
incremental = false
overflow-checks = false
