[package]
name = "byte-knight"
version = "4.0.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
engine = { workspace = true }
chess = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
rayon = { workspace = true }
shadow-rs = { version = "1.7.1", default-features = false }

[build-dependencies]
shadow-rs = "1.7.1"
