[package]
name = "byte-knight"
version = "4.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
engine = { workspace = true }
chess = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }
uci-parser = { workspace = true, features = ["parse-go-perft", "parse-position-kiwipete", "types", "clamp-negatives"] }
shadow-rs = { version = "2.0.0", default-features = false }
rapidhash = { workspace = true }

[build-dependencies]
shadow-rs = "2.0.0"

[features]
tuning = []
