name: Build release binaries

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false
        default: "9.99.99"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            extension: ""
          - os: macos-latest
            toolchain: nightly
            target: aarch64-apple-darwin
            extension: ""
          - os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc
            extension: ".exe"
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ inputs.tag || github.ref_name }}
      RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}
    steps:
      - uses: actions/checkout@v6

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Stage release binary
        shell: bash
        run: |
          mkdir -p ./artifacts
          cp ./target/${{ matrix.target }}/release/byte-knight${{ matrix.extension }} \
             ./artifacts/byte-knight-${VERSION}-${{ matrix.target }}${{ matrix.extension }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: byte-knight-${{ matrix.target }}${{ matrix.extension }}
          path: ./artifacts/byte-knight-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.extension }}
          retention-days: 1

      - name: Upload to release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v3
        with:
          files: ./artifacts/byte-knight-${{ env.VERSION }}-${{ matrix.target }}${{ matrix.extension }}
